Parallelism with Github Actions (#4)

diff --git a/.github/workflows/ccpp.yml b/.github/workflows/ccpp.yml
--- a/.github/workflows/ccpp.yml
+++ b/.github/workflows/ccpp.yml
@@ -1,4 +1,4 @@
-name: C/C++ CI
+name: Execution sequential
 
 on: [push]
 
@@ -9,9 +9,24 @@ jobs:
     
     steps:
     - uses: actions/checkout@v1
-    - name: make
+    - uses: actions/checkout@v1
+    - name: Execute ls -la
+      run: ls -la
+    - name: Check if README exist
+      run: sh -f README.md  && echo "Found" || echo "Not found"
+    - name: Check if Makefile exist
+      run: sh -f Makefile.md && echo "Found" || echo "Not found"
+    - name: clean project
+      run: make clean
+    - name: compile the project
       run: make
-    - name: Create a matrix file
-      run: ./gmat 1000 1000
-    - name: Execute main omp
-      run: ./main_omp 1000x1000-mat.map 1000x1000-mat.map
+    - name: Create a 200x200 matrix file
+      run: ./gmat 200 200
+    - name: Create a 2000x2000 matrix file
+      run: ./gmat 2000 2000
+    - name: Execute main_omp with a 200x200 matrix
+      run: ./main_omp 200x200-mat.map 200x200-mat.map 2
+    - name: Execute main_omp with a 2000x2000 matrix
+      run: ./main_omp 2000x2000-mat.map 2000x2000-mat.map 2
+    - name: Execute main_omp with a 2000x2000 matrix and 4 threads
+      run: ./main_omp 2000x2000-mat.map 2000x2000-mat.map 4
